name             'cookbook-remi'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures yum remi and remi-php55'
version          '0.1.0'
